org: tdaiforwork
app: tdai_book_store
service: tdai-book-store

frameworkVersion: '2'

plugins:
  - serverless-offline


package:
  excludeDevDependencies: true
  exclude:
    - .github/**
    - .byc_output/**
    - .vsscode/**
    - charts/**
    - devops/**
    - patches/**
    - src/**
    - tests/**
    - tracker/**
    - .cfignore
    - .editorconfig
    - .env
    - .env1
    - .gitignore
    - debug.log
    - jest.config.js
    - README.md
    - test.env
    - tsconfig.json
    - tslint.json
    - tsoa.json

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: '20201221'
  environment:
    APP: book-store
    STAGE: dev
    MODE: SLS-AWS
    NODE_ENV: development
    PORT: 8082

functions:
  api:
    handler: dist/handler.handler
    events:
      - http:
          path: /
          method: ANY
      - http:
          path: /{proxy+}
          method: ANY
